# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_url', models.URLField()),
                ('user_url', models.URLField()),
                ('follow', models.BooleanField()),
                ('musicfile', models.FileField(upload_to=b'')),
            ],
        ),
    ]
