# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='track_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='user_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
