# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160519_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
