# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160519_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
